site_name: 西电计科传承手册
site_url: https://XDUCS.github.io/
repo_name: XDUCS
repo_url: https://github.com/XDUCS/XDUCS.github.io.git
theme:
  name: material
  custom_dir: overrides
  language: zh
  favicon: Images/favicon.png
  icon:
    logo: material/library
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

copyright: Copyright &copy; 2024 Xidian CS
nav:
  - 主页:
    - index.md
    - 站点简介: Home/Profile.md
    - 站点前言: Home/Introduction.md
    - 贡献指南: Home/Contributing.md
    - 课程模板: Home/Template.md
    - 写作语法: Home/WritingUsage.md
  - 计科大类基础课:
    - CSBasic/index.md
    - 思政军体课:
      - 习近平新时代中国特色社会主义思想概论: CSBasic/Politics/XiIdeas.md
    - 通识选修课: CSBasic/General/index.md
    - 数理基础课:
      - 高等数学(I): CSBasic/Maths/AdvancedMath1.md
    - 国际双创课: CSBasic/Internation/index.md
    - 专业基础课:
      - CSBasic/ProfBase/index.md
      - 计算机导论与程序设计: CSBasic/ProfBase/ComputerIntroduction.md
    - 专业核心课:
      - CSBasic/ProfCore/index.md
      - 数据结构: CSBasic/ProfCore/DataStructure.md
      - 微机原理与系统设计: CSBasic/ProfCore/MicroComputer.md
    - 专业任选课:
      - CSBasic/ProfAny/index.md
      - 组合数学: CSBasic/ProfAny/Combinatorics.md
  
  - 计科嵌入式系统方向:
    - EmbeddedSystem/index.md
    - 自主可控嵌入式系统设计: EmbeddedSystem/EmbeddedSystem.md
    - 数字信号处理: EmbeddedSystem/DigitalSignal.md
  - 计科软件与理论方向:
    - SoftwareTheory/index.md
  - 计科大数据智能方向:
    - Intelligence/index.md
  - 计科网络与信息安全方向:
    - Network/index.md
  - 计科保研:
    - 2021级保研情况:
      - 夏令营成绩排名: 
        - 计科嵌入式系统: BaoYan/Summer/EmbeddSystem.md
        - 计科网络与信息安全: BaoYan/Summer/Network.md
        - 计科软件与理论: BaoYan/Summer/Software.md
        - 计科大数据智能: BaoYan/Summer/DataIntel.md
        - 计科卓越: BaoYan/Summer/ZhuoYue.md
        - 计科拔尖: BaoYan/Summer/BaJian.md
      - 预推免成绩排名: 
        - 计科嵌入式系统: BaoYan/Prerecom/CS/EmbeddSystem.md
        - 计科网络与信息安全: BaoYan/Prerecom/CS/Network.md
        - 计科软件与理论: BaoYan/Prerecom/CS/Software.md
        - 计科大数据智能: BaoYan/Prerecom/CS/DataIntel.md
        - 计科卓越: BaoYan/Prerecom/CS/ZhuoYue.md
        - 计科拔尖: BaoYan/Prerecom/CS/BaJian.md
        - 软工云计算: BaoYan/Prerecom/SE/Compute.md
        - 软工嵌入式: BaoYan/Prerecom/SE/EmbeddSystem.md
        - 软工网络与信息安全: BaoYan/Prerecom/SE/Network.md
        - 软工web: BaoYan/Prerecom/SE/Web.md
        - 数据科学: BaoYan/Prerecom/SE/DS.md
        - 物联网: BaoYan/Prerecom/SE/IOT.md
      - 各专业保研名单: BaoYan/Recom.md
      - 保研经验贴: 
        - Yi Zhang: BaoYan/Experience/2021Level/YZhang.md
        - Zhihao Li: BaoYan/Experience/2021Level/ZHao.md
  - 导师评价:
    - Tutors/index.md
    - 推荐篇: Tutors/Recom/index.md
    - 避雷篇: Tutors/Oppose/index.md

plugins:
  - search
  - table-reader
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/XDUCS
    - icon: fontawesome/solid/paper-plane
      link: mailto:xducs@hotmail.com
    - icon: fontawesome/brands/mastodon
      link: https://xducs.github.io/  

markdown_extensions:
  - tables
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - Configuration/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - Configuration/stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
